export const types = {
    SET_VIEW_MODAL_VISIBLE: 'SET_VIEW_MODAL_VISIBLE',
    SET_ADD_MODAL_VISIBLE: 'SET_ADD_MODAL_VISIBLE',
    SET_EDIT_MODAL_VISIBLE: 'SET_EDIT_MODAL_VISIBLE',
    SET_DELETE_MODAL_VISIBLE: 'SET_DELETE_MODAL_VISIBLE',
    SET_ASSIGN_MODAL_VISIBLE: 'SET_ASSIGN_MODAL_VISIBLE',
    SET_UNASSIGN_MODAL_VISIBLE: 'SET_UNASSIGN_MODAL_VISIBLE',
    SET_REFETCH_SUCCESS: 'SET_REFETCH_SUCCESS',
};